# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        logistrix_db_provider:
            entity:
                class: LogistrixBundle:User
                property: username

    firewalls:

        # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            form_login:
                login_path: logistrix_login
                check_path: logistrix_login_check
            provider: logistrix_db_provider

        login_firewall:
            pattern:   ^/login$
            anonymous: ~

        secured_area:
            pattern:    ^/
            form_login: ~

    access_control:
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logistrix, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        LogistrixBundle\Entity\User:
            algorithm: bcrypt
