LogistrixBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 64
        password:
            type: string
            length: 64
        email:
            type: string
            length: 64
            unique: true
            nullable: false
        isActive:
            type: boolean
        roles:
            type: text